package com.ysd.springcloud.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("pro_event", "id", Event.class);
		arp.addMapping("pro_folder", "id", Folder.class);
		arp.addMapping("pro_letter", "id", Letter.class);
		arp.addMapping("pro_weekly_newspaper", "id", WeeklyNewspaper.class);
		arp.addMapping("pro_picture", "id", Picture.class);
		arp.addMapping("pro_problem", "id", Problem.class);
		arp.addMapping("pro_vrshow", "id", Vrshow.class);
		arp.addMapping("pro_organizer", "id", Organizer.class);
		arp.addMapping("sys_app", "id", App.class);
		arp.addMapping("sys_app_token", "id", AppToken.class);
		arp.addMapping("log_document", "id", LogDocument.class);
		/*指挥页视频监控*/
		arp.addMapping("cmd_surve_vdo", "id", SurveVdo.class);
		/*指挥页考勤统计*/
		arp.addMapping("cmd_check_in_count", "id", CheckInCount.class);
	}
}

