package com.ysd.springcloud.common.model;

import com.ysd.springcloud.common.model.base.BaseFolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Folder extends BaseFolder<Folder> {
	
	public static final String ENTITY_P_EVENT = "proEvent";    // 项目事件主目录
	public static final String ENTITY_I_EVENT = "event";       // 项目事件子目录
	public static final String ENTITY_P_VRSHOW = "proVrshow";  // VR展示主目录
	public static final String ENTITY_I_VRSHOW = "vrshow";     // VR展示子目录
	public static final String ENTITY_P_LETTER = "proLetter";	// 项目函件主目录
	public static final String ENTITY_I_LETTER = "letter";		// 项目函件子目录
	public static final String ENTITY_P_PAPER = "proPaper";		// 项目周报主目录
	public static final String ENTITY_I_PAPER = "paper";		// 项目周报子目录
	
}
