package com.ysd.springcloud.common.model;

import com.ysd.springcloud.common.model.base.BaseOrganizer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Organizer extends BaseOrganizer<Organizer> {
	
}
