package com.ysd.springcloud.common.model;

import com.ysd.springcloud.common.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	
	public static final int TYPE_AERIAL = 1;		// 现场航拍
	public static final int TYPE_EFFECT = 2;		// 效果图
	public static final int TYPE_PHOTO = 3;			// 项目照片
	
}
