package com.ysd.springcloud.common.model;

import com.ysd.springcloud.common.model.base.BaseSurveVdo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SurveVdo extends BaseSurveVdo<SurveVdo> {
	
	/*是否删除*/
	public static final int IS_DEL = 1;
	/*是否启用*/
	public static final int IS_ACT= 1;
}
