package com.ysd.springcloud.common.model;

import com.ysd.springcloud.common.model.base.BaseVrshow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vrshow extends BaseVrshow<Vrshow> {
	
}
