package com.ysd.springcloud.common.model;

import com.ysd.springcloud.common.model.base.BaseWeeklyNewspaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeeklyNewspaper extends BaseWeeklyNewspaper<WeeklyNewspaper> {
	
}
