package com.ysd.overview.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogDocument<M extends BaseLogDocument<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public void setPathName(java.lang.String pathName) {
		set("pathName", pathName);
	}
	
	public java.lang.String getPathName() {
		return getStr("pathName");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreatorName(java.lang.String creatorName) {
		set("creatorName", creatorName);
	}
	
	public java.lang.String getCreatorName() {
		return getStr("creatorName");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setStageId(java.lang.String stageId) {
		set("stageId", stageId);
	}
	
	public java.lang.String getStageId() {
		return getStr("stageId");
	}

	public void setStageName(java.lang.String stageName) {
		set("stageName", stageName);
	}
	
	public java.lang.String getStageName() {
		return getStr("stageName");
	}

	public void setOrganization(java.lang.String organization) {
		set("organization", organization);
	}
	
	public java.lang.String getOrganization() {
		return getStr("organization");
	}

	public void setOrganizationId(java.lang.String organizationId) {
		set("organizationId", organizationId);
	}
	
	public java.lang.String getOrganizationId() {
		return getStr("organizationId");
	}

}
