package com.ysd.springcloud.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cmd_check_in_count", "id", CmdCheckInCount.class);
		arp.addMapping("cmd_surve_vdo", "id", CmdSurveVdo.class);
		arp.addMapping("labor_worker", "id", LaborWorker.class);
		arp.addMapping("log_document", "id", LogDocument.class);
		arp.addMapping("log_problem", "id", LogProblem.class);
		arp.addMapping("pro_event", "id", ProEvent.class);
		arp.addMapping("pro_folder", "id", ProFolder.class);
		arp.addMapping("pro_letter", "id", ProLetter.class);
		arp.addMapping("pro_menu", "id", ProMenu.class);
		arp.addMapping("pro_organizer", "id", ProOrganizer.class);
		arp.addMapping("pro_picture", "id", ProPicture.class);
		arp.addMapping("pro_problem", "id", ProProblem.class);
		arp.addMapping("pro_prop", "id", ProProp.class);
		arp.addMapping("pro_vrshow", "id", ProVrshow.class);
		arp.addMapping("pro_weekly_newspaper", "id", ProWeeklyNewspaper.class);
		arp.addMapping("sys_app", "id", SysApp.class);
		arp.addMapping("sys_app_token", "id", SysAppToken.class);
	}
}

