package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseCmdCheckInCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmdCheckInCount extends BaseCmdCheckInCount<CmdCheckInCount> {
	
}
