package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseCmdSurveVdo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmdSurveVdo extends BaseCmdSurveVdo<CmdSurveVdo> {
	
}
