package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseLaborWorker;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LaborWorker extends BaseLaborWorker<LaborWorker> {
	
}
