package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseLogDocument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogDocument extends BaseLogDocument<LogDocument> {
	
}
