package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseLogProblem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogProblem extends BaseLogProblem<LogProblem> {
	
}
