package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProEvent extends BaseProEvent<ProEvent> {
	
}
