package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProFolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProFolder extends BaseProFolder<ProFolder> {
	
}
