package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProLetter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProLetter extends BaseProLetter<ProLetter> {
	
}
