package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProMenu extends BaseProMenu<ProMenu> {
	
}
