package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProOrganizer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProOrganizer extends BaseProOrganizer<ProOrganizer> {
	
}
