package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProProblem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProProblem extends BaseProProblem<ProProblem> {
	
}
