package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProPicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProPicture extends BaseProPicture<ProPicture> {
	
}
