package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProProp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProProp extends BaseProProp<ProProp> {
	
}
