package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProVrshow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProVrshow extends BaseProVrshow<ProVrshow> {
	
}
