package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseProWeeklyNewspaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProWeeklyNewspaper extends BaseProWeeklyNewspaper<ProWeeklyNewspaper> {
	
}
