package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseSysApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysApp extends BaseSysApp<SysApp> {
	
}
