package com.ysd.springcloud.model;

import com.ysd.springcloud.model.base.BaseSysAppToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAppToken extends BaseSysAppToken<SysAppToken> {
	
}
