server:
  port: 9522
#  servlet:
#    context-path: /jfinal
spring:
  application:
    name: nacos-payment-provider-me
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    #    url: jdbc:mysql://localhost:3306/db2019?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    #    username: root
    #    password: root
    url: jdbc:mysql://172.18.148.80:10010/ysd_overview?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: bim
    password: bim@prod1&2019$

arp.jdbc-url : jdbc:mysql://localhost:9253/ysd_overview?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
arp.username : root
arp.password : prod1&2019$
arp.is-dev-mode: true



