package com.ysd.springcloud.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrganizer<M extends BaseOrganizer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setParties(java.lang.String parties) {
		set("parties", parties);
	}
	
	public java.lang.String getParties() {
		return getStr("parties");
	}

	public void setUnitName(java.lang.String unitName) {
		set("unitName", unitName);
	}
	
	public java.lang.String getUnitName() {
		return getStr("unitName");
	}

	public void setUnitCode(java.lang.String unitCode) {
		set("unitCode", unitCode);
	}
	
	public java.lang.String getUnitCode() {
		return getStr("unitCode");
	}

	public void setContacts(java.lang.String contacts) {
		set("contacts", contacts);
	}
	
	public java.lang.String getContacts() {
		return getStr("contacts");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}
	
	public java.lang.String getFax() {
		return getStr("fax");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

}
