package com.ysd.springcloud.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVrshow<M extends BaseVrshow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setViewPath(java.lang.String viewPath) {
		set("viewPath", viewPath);
	}
	
	public java.lang.String getViewPath() {
		return getStr("viewPath");
	}

	public void setPicPath(java.lang.String picPath) {
		set("picPath", picPath);
	}
	
	public java.lang.String getPicPath() {
		return getStr("picPath");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

	public void setStage(java.lang.String stage) {
		set("stage", stage);
	}
	
	public java.lang.String getStage() {
		return getStr("stage");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreatorName(java.lang.String creatorName) {
		set("creatorName", creatorName);
	}
	
	public java.lang.String getCreatorName() {
		return getStr("creatorName");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("createAt", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("createAt");
	}

	public void setV2Stage(java.lang.Integer v2Stage) {
		set("v2_stage", v2Stage);
	}
	
	public java.lang.Integer getV2Stage() {
		return getInt("v2_stage");
	}

}
