package com.ysd.springcloud.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSurveVdo<M extends BaseSurveVdo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setVdoPath(java.lang.String vdoPath) {
		set("vdo_path", vdoPath);
	}
	
	public java.lang.String getVdoPath() {
		return getStr("vdo_path");
	}

	public void setPicPath(java.lang.String picPath) {
		set("pic_path", picPath);
	}
	
	public java.lang.String getPicPath() {
		return getStr("pic_path");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

	public void setIsAct(java.lang.Boolean isAct) {
		set("is_act", isAct);
	}
	
	public java.lang.Boolean getIsAct() {
		return get("is_act");
	}

	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}
	
	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}

	public void setCreateAt(java.util.Date createAt) {
		set("create_at", createAt);
	}
	
	public java.util.Date getCreateAt() {
		return get("create_at");
	}

	public void setUpdateAt(java.util.Date updateAt) {
		set("update_at", updateAt);
	}
	
	public java.util.Date getUpdateAt() {
		return get("update_at");
	}

}
