package com.ysd.springcloud.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCmdCheckInCount<M extends BaseCmdCheckInCount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreatorNum(java.lang.String creatorNum) {
		set("creator_num", creatorNum);
	}
	
	public java.lang.String getCreatorNum() {
		return getStr("creator_num");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

	public void setGmtDate(java.util.Date gmtDate) {
		set("gmt_date", gmtDate);
	}
	
	public java.util.Date getGmtDate() {
		return get("gmt_date");
	}

	public void setCheckInNum(java.lang.Integer checkInNum) {
		set("check_in_num", checkInNum);
	}
	
	public java.lang.Integer getCheckInNum() {
		return getInt("check_in_num");
	}

	public void setSceneNum(java.lang.Integer sceneNum) {
		set("scene_num", sceneNum);
	}
	
	public java.lang.Integer getSceneNum() {
		return getInt("scene_num");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
