package com.ysd.springcloud.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProProblem<M extends BaseProProblem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public void setSpecialty(java.lang.String specialty) {
		set("specialty", specialty);
	}
	
	public java.lang.String getSpecialty() {
		return getStr("specialty");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setBuild(java.lang.String build) {
		set("build", build);
	}
	
	public java.lang.String getBuild() {
		return getStr("build");
	}

	public void setFloor(java.lang.String floor) {
		set("floor", floor);
	}
	
	public java.lang.String getFloor() {
		return getStr("floor");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public void setBeginTime(java.util.Date beginTime) {
		set("beginTime", beginTime);
	}
	
	public java.util.Date getBeginTime() {
		return get("beginTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setContactMan(java.lang.String contactMan) {
		set("contactMan", contactMan);
	}
	
	public java.lang.String getContactMan() {
		return getStr("contactMan");
	}

	public void setContactNum(java.lang.String contactNum) {
		set("contactNum", contactNum);
	}
	
	public java.lang.String getContactNum() {
		return getStr("contactNum");
	}

	public void setBelongsGroup(java.lang.String belongsGroup) {
		set("belongsGroup", belongsGroup);
	}
	
	public java.lang.String getBelongsGroup() {
		return getStr("belongsGroup");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

}
