package com.ysd.springcloud.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLaborWorker<M extends BaseLaborWorker<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setWorkday(java.util.Date workday) {
		set("workday", workday);
	}
	
	public java.util.Date getWorkday() {
		return get("workday");
	}

	public void setRealNum(java.lang.Integer realNum) {
		set("realNum", realNum);
	}
	
	public java.lang.Integer getRealNum() {
		return getInt("realNum");
	}

	public void setPlanNum(java.lang.Integer planNum) {
		set("planNum", planNum);
	}
	
	public java.lang.Integer getPlanNum() {
		return getInt("planNum");
	}

	public void setCarft(java.lang.String carft) {
		set("carft", carft);
	}
	
	public java.lang.String getCarft() {
		return getStr("carft");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

}
