package com.ysd.overview.common.model;

import com.ysd.overview.common.model.base.BaseApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class App extends BaseApp<App> {
	
	public static final int STATUS_NO = 0;			// 禁用
	public static final int STATUS_OK = 1;			// 启用

	public boolean isStatusNo() {
		return getStatus() == STATUS_NO;
	}
	
	public boolean isStatusOk() {
		return getStatus() == STATUS_OK;
	}
	
}
