package com.ysd.overview.common.model;

import com.ysd.overview.common.model.base.BaseAppToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppToken extends BaseAppToken<AppToken> {
	
}
