package com.ysd.overview.common.model;

import com.ysd.overview.common.model.base.BaseCheckInCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckInCount extends BaseCheckInCount<CheckInCount> {
	//删除
	public static final int IS_DELETED = 1;
}
