package com.ysd.overview.common.model;

import com.ysd.overview.common.kit.JsoupKit;
import com.ysd.overview.common.model.base.BaseEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Event extends BaseEvent<Event> {
	
	/**
	 * 过滤 title content 字段的 html 标记，防止 XSS 攻击
	 */
	protected void filter(int filterBy) {
		JsoupKit.filterTitleAndContent(this);
	}
	
}
