package com.ysd.overview.common.model;

import com.ysd.overview.common.model.base.BaseLetter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Letter extends BaseLetter<Letter> {
	
}
