package com.ysd.overview.common.model;

import com.ysd.overview.common.model.base.BaseProblem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Problem extends BaseProblem<Problem> {
	
	public static final int ACTION_IMPORT = 1;			// 导入
	public static final int ACTION_EXPORT = 2;			// 导出
	public static final int ACTION_START = 0;			// 启动
	public static final int ACTION_DONE = 1;			// 完成
	
}
